/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import bean.Category;
import controller.ScreenSwitchController;
import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author Luong Huy Thong
 */
public class MainJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public MainJFrame() {
        initComponents();
        setTitle("QUẢN LÝ SINH VIÊN");
        ScreenSwitchController controller = new ScreenSwitchController(jpnView);
        controller.setDashboard(jpnHomePage, jlbHomePage);
        
        List<Category> listItem = new ArrayList<>();
        listItem.add(new Category("HomePage", jpnHomePage, jlbHomePage));
        listItem.add(new Category("Student", jpnStudent, jlbStudent));
        listItem.add(new Category("Course", jpnCourse, jlbCourse));
        listItem.add(new Category("Classes",  jpnClasses, jlbClasses));
        listItem.add(new Category("Statistic", jpnStatistic, jlbStatistic));
        controller.setEvent(listItem);
                
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        JpnRoot = new javax.swing.JPanel();
        jpnMenu = new javax.swing.JPanel();
        jpnHomePage = new javax.swing.JPanel();
        jlbHomePage = new javax.swing.JLabel();
        jpnStudent = new javax.swing.JPanel();
        jlbStudent = new javax.swing.JLabel();
        jpnCourse = new javax.swing.JPanel();
        jlbCourse = new javax.swing.JLabel();
        jpnClasses = new javax.swing.JPanel();
        jlbClasses = new javax.swing.JLabel();
        jpnStatistic = new javax.swing.JPanel();
        jlbStatistic = new javax.swing.JLabel();
        jpnHome = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jpnView = new javax.swing.JPanel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JpnRoot.setBackground(new java.awt.Color(204, 255, 255));

        jpnMenu.setBackground(new java.awt.Color(25, 21, 16));

        jpnHomePage.setBackground(new java.awt.Color(60, 170, 85));

        jlbHomePage.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbHomePage.setForeground(new java.awt.Color(255, 255, 255));
        jlbHomePage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_important_devices_white_24dp.png"))); // NOI18N
        jlbHomePage.setText("Màn hình chính");

        javax.swing.GroupLayout jpnHomePageLayout = new javax.swing.GroupLayout(jpnHomePage);
        jpnHomePage.setLayout(jpnHomePageLayout);
        jpnHomePageLayout.setHorizontalGroup(
            jpnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomePageLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnHomePageLayout.setVerticalGroup(
            jpnHomePageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnStudent.setBackground(new java.awt.Color(60, 170, 85));

        jlbStudent.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbStudent.setForeground(new java.awt.Color(255, 255, 255));
        jlbStudent.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_account_circle_white_24dp.png"))); // NOI18N
        jlbStudent.setText("Quản lý Sinh Viên");

        javax.swing.GroupLayout jpnStudentLayout = new javax.swing.GroupLayout(jpnStudent);
        jpnStudent.setLayout(jpnStudentLayout);
        jpnStudentLayout.setHorizontalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStudentLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnStudentLayout.setVerticalGroup(
            jpnStudentLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStudent)
        );

        jpnCourse.setBackground(new java.awt.Color(60, 170, 85));

        jlbCourse.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbCourse.setForeground(new java.awt.Color(255, 255, 255));
        jlbCourse.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_all_inbox_white_24dp.png"))); // NOI18N
        jlbCourse.setText("Quản lý khóa học");

        javax.swing.GroupLayout jpnCourseLayout = new javax.swing.GroupLayout(jpnCourse);
        jpnCourse.setLayout(jpnCourseLayout);
        jpnCourseLayout.setHorizontalGroup(
            jpnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnCourseLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnCourseLayout.setVerticalGroup(
            jpnCourseLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbCourse)
        );

        jpnClasses.setBackground(new java.awt.Color(60, 170, 85));

        jlbClasses.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbClasses.setForeground(new java.awt.Color(255, 255, 255));
        jlbClasses.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_store_mall_directory_white_24dp.png"))); // NOI18N
        jlbClasses.setText("Quản lý lớp học");

        javax.swing.GroupLayout jpnClassesLayout = new javax.swing.GroupLayout(jpnClasses);
        jpnClasses.setLayout(jpnClassesLayout);
        jpnClassesLayout.setHorizontalGroup(
            jpnClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnClassesLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnClassesLayout.setVerticalGroup(
            jpnClassesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnStatistic.setBackground(new java.awt.Color(60, 170, 85));

        jlbStatistic.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jlbStatistic.setForeground(new java.awt.Color(255, 255, 255));
        jlbStatistic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_pie_chart_white_24dp.png"))); // NOI18N
        jlbStatistic.setText("Thống kê dữ liệu");

        javax.swing.GroupLayout jpnStatisticLayout = new javax.swing.GroupLayout(jpnStatistic);
        jpnStatistic.setLayout(jpnStatisticLayout);
        jpnStatisticLayout.setHorizontalGroup(
            jpnStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnStatisticLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jlbStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jpnStatisticLayout.setVerticalGroup(
            jpnStatisticLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jlbStatistic, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jpnHome.setBackground(new java.awt.Color(179, 63, 65));

        jLabel1.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/baseline_supervised_user_circle_white_24dp.png"))); // NOI18N
        jLabel1.setText("QUẢN LÝ SINH VIÊN");

        javax.swing.GroupLayout jpnHomeLayout = new javax.swing.GroupLayout(jpnHome);
        jpnHome.setLayout(jpnHomeLayout);
        jpnHomeLayout.setHorizontalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnHomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(22, 22, 22))
        );
        jpnHomeLayout.setVerticalGroup(
            jpnHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 54, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jpnMenuLayout = new javax.swing.GroupLayout(jpnMenu);
        jpnMenu.setLayout(jpnMenuLayout);
        jpnMenuLayout.setHorizontalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jpnHomePage, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnCourse, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnStudent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnClasses, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jpnStatistic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addComponent(jpnHome, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jpnMenuLayout.setVerticalGroup(
            jpnMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpnMenuLayout.createSequentialGroup()
                .addComponent(jpnHome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jpnHomePage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnCourse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnStudent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnClasses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jpnStatistic, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jpnView.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout jpnViewLayout = new javax.swing.GroupLayout(jpnView);
        jpnView.setLayout(jpnViewLayout);
        jpnViewLayout.setHorizontalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 513, Short.MAX_VALUE)
        );
        jpnViewLayout.setVerticalGroup(
            jpnViewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 549, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout JpnRootLayout = new javax.swing.GroupLayout(JpnRoot);
        JpnRoot.setLayout(JpnRootLayout);
        JpnRootLayout.setHorizontalGroup(
            JpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JpnRootLayout.createSequentialGroup()
                .addComponent(jpnMenu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JpnRootLayout.setVerticalGroup(
            JpnRootLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jpnMenu, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jpnView, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(JpnRoot, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(MainJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new MainJFrame().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JpnRoot;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel jlbClasses;
    private javax.swing.JLabel jlbCourse;
    private javax.swing.JLabel jlbHomePage;
    private javax.swing.JLabel jlbStatistic;
    private javax.swing.JLabel jlbStudent;
    private javax.swing.JPanel jpnClasses;
    private javax.swing.JPanel jpnCourse;
    private javax.swing.JPanel jpnHome;
    private javax.swing.JPanel jpnHomePage;
    private javax.swing.JPanel jpnMenu;
    private javax.swing.JPanel jpnStatistic;
    private javax.swing.JPanel jpnStudent;
    private javax.swing.JPanel jpnView;
    // End of variables declaration//GEN-END:variables
}
